### ISSUE TITLE
Finish setting up fastpages for Kubeflow

### ISSUE THREAD

**Issue by jlewi** [kubeflow/blog#1]
Per kubeflow/community#316 we decided to setup fastpages to start experimenting it with as alternative to medium for blogging.

The repo has been created from the template but we still have to do all the remaining work to set this up.

**Comment by jlewi** [comment]
@hamelsmu I recreated the repo as kubeflow/blog. I created the DNS entries.

**Comment by jlewi** [comment]
@hamelsmu per 
https://www.netlify.com/blog/2017/02/28/to-www-or-not-www/?_ga=2.97876639.105223730.1594790016-1839953510.1592346425

I don't think we want to setup an apex domain for fastpages because we want the apex domain to be for our website which should be www.kubeflow.org.

So I think we just need a CNAME record pointing at: kubeflow.github.io

**Comment by jlewi** [comment]
I deleted the A record and added the CNAME record. Lets give it a chance to propogate and see what happens.

**Comment by jlewi** [comment]
Everything looks to be working.

```
nslookup blog.kubeflow.org
Server:		127.0.0.1
Address:	127.0.0.1#53

Non-authoritative answer:
blog.kubeflow.org	canonical name = kubeflow.github.io.
Name:	kubeflow.github.io
Address: 185.199.109.153
Name:	kubeflow.github.io
Address: 185.199.110.153
Name:	kubeflow.github.io
Address: 185.199.111.153
Name:	kubeflow.github.io
Address: 185.199.108.153
```

**Comment by hamelsmu** [comment]
I believe I can close this issue
