### ISSUE TITLE
Kubeflow 1.1 Blog Post

### ISSUE THREAD

**Issue by jbottum** [kubeflow/blog#12]
Opening this issue will trigger GitHub Actions to fetch the lastest version of [fastpages](https://github.com/fastai/fastpages).  More information will be provided in forthcoming comments below.
[Kubeflow 1.1 Blog Post Material (1).docx](https://github.com/kubeflow/blog/files/4929030/Kubeflow.1.1.Blog.Post.Material.1.docx)

**Comment by jbottum** [comment]
@hamelsmu Hi Hamel - I would like to use fastpages to get reviews, edits and approvals for our 1.1 blog post.   I was thinking that I should upload the docs (as in cell above) and then start to as reviewers to review and edit, then I would ask approvers to approve.    Before I start the content review, do you have any advice on how to make the content (in word doc) available to reviewers?

**Comment by hamelsmu** [comment]
Hi @jbottum perhaps you would like to convert your word doc to a markdown post?  

Can you please read the [fastpages README](https://github.com/fastai/fastpages) to understand how it works?   I suggest converting your word document to markdown, you can do this with fastpages by cloning the project locally and placing your word document in the `/_word` folder, and running the command `make server` which will allow you to preview your post.   I would then grab the generated markdown post that appears in `_posts` related to word document and commit **that file only to a branch and make a PR for review**.  (Normally you would just leave your word doc in there if it was your personal post, but since we want to do code reviews for this site its best to use markdown.  

How does that sound?  cc: @jlewi

**Comment by jbottum** [comment]
**Kubeflow 1.1 improves ML Workflow Productivity, Isolation &amp; Security, and GitOps**

The Kubeflow Community&#39;s delivery of Kubeflow 1.1 offers users valuable ML workflow automation with Fairing and Kale along with MXNet and XGBoost distributed training operators. It extends isolation and security through the delivery of multi-user pipelines, CVE scanning, and support for Google&#39;s Private GKE and Anthos. 1.1 provides a foundation for consistent and repeatable installation and operations using GitOps methodologies powered by blueprints and kpt primitives.

The ML productivity enhancements in 1.1 include end-to-end workflows using Fairing and Kale. The Fairing workflow enables users to build, train and deploy models from a notebook and [Fairing improvements](https://github.com/kubeflow/fairing/releases/tag/v1.0.1) include the support of configuring environment variables and mounting secrets. Fairing also added a config map for a deployer and bug fixes for TensorRTSpec. The workflows enabled by [Kale](https://github.com/kubeflow-kale/kale) include the ability to write model code in a notebook and then automatically build a Kubeflow pipeline that deploys, trains and tunes that model efficiently, using Katib and cached pipeline steps. Kubeflow 1.1 also delivers stable release deliveries of [MXNet and XGBoost operators](https://github.com/kubeflow/common/blob/master/ROADMAP.md), which simplify distributed training on multiple nodes and speeds model creation.

The isolation and security feature deliveries include Private GKE and Anthos support, a stable version of Kubeflow Pipelines with [Multi-User Kubeflow Pipelines](https://github.com/kubeflow/pipelines/projects/1) support, and a process for Kubeflow container image scanning, [CVE reporting](https://docs.google.com/spreadsheets/d/1ijWIyjGQpDy68-vjBmLyFY0U1oGCT--A0nVGgzLGDhU/edit#gid=0), and an optional process for distroless image creation. 1.1 also includes [options for authentication and authorization](https://github.com/kubeflow/kubeflow/issues/4960). This includes the option for administrators to turn off self-service namespace creation mode, as admins may have other processes for namespace creation. The Community also developed a best practice to build user authorization in Kubeflow web apps using subject access review.

The installation and operations of Kubeflow have been enhanced to support GitOps methodologies. Several Kubeflow platform providers and software support vendors are developing time-saving GitOps processes to simplify and codify the installation, configuration and operations of the various layers in the Kubeflow 1.1 hardware and software stack. Some examples are provided in the next section.

**More details and 1.1 tutorials**

Kubeflow 1.1 includes many technical enhancements, which are being delivered via the Community&#39;s release process. Details on the application feature development can be found in the [1.1 KanBan Board](https://github.com/orgs/kubeflow/projects/26) and in the [Kubeflow Roadmap](https://github.com/kubeflow/kubeflow/blob/master/ROADMAP.md). As the Kubeflow application improvements are merged, the platform teams (GCP, AWS, IBM, Red Hat, Azure, and Arrikto MiniKF) are working to validate the feature improvements on their respective environments.

Kubeflow 1.1 demo scripts and workflow tutorials are available as validated by the individual platforms. Please find those below:

- [Kubeflow 1.1 Tutorial for Automated Hyperparameter Tuning, Multi-user Pipelines, Pipeline Caching](https://medium.com/@sfiora/5821747f4fcb)
- [GitOps for Kubeflow 1.1 on AWS EKS](http://docs.arrikto.com/integrations/kubeflow.html)

1.1 users can also leverage several other Kubeflow EcoSystem tools including:

- [Seldon Core 1.1](https://docs.seldon.io/projects/seldon-core/en/latest/reference/release-1.1.0.html), which handles scaling to thousands of production ML models and provides advanced ML capabilities including Advanced Metrics, Request Logging, Explainers, Outlier Detectors, A/B Tests, Canaries and more.
- The [Feast](https://feast.dev/) 0.3 feature store, which allows ML teams to define, manage, discover, and serve ML features.

Quick Links

**What&#39;s Coming and Getting involved**

The Community has started planning for its next release. Although we have a nice backlog of issues, our process includes discussions and surveys with users and contributors to validate use cases and their value.

The Community continues to refine its governance and refine this proposal, [Proposal for Kubeflow WG Guidelines/Governance](https://github.com/kubeflow/community/pull/348). We are actively developing Working Group team charters, tech leads, chairs and members. We look forward to this growth.

The following provides some helpful links to those looking to get involved with the Kubeflow Community:

- Join the [Kubeflow Slack channel](https://app.slack.com/client/T7QLHSH6U/C7REE0EHK/thread/C7REE0EHK-1554222405.030500)
- Join the [kubeflow-discuss mailing list](https://groups.google.com/g/kubeflow-discuss)
- Attend a [weekly community meeting](https://github.com/kubeflow/community)

If you have questions, run into issues, please leverage the Slack channel and/or submit bugs via [Kubeflow on GitHub](https://github.com/kubeflow). Thanks from all of us in the Community, and we look forward to your success with Kubeflow 1.1.

**Comment by hamelsmu** [comment]
Josh looks good to me want to transfer this into markdown for a pull
request?
