### ISSUE TITLE
Unhide 1.1 Blog post and update with Multi-user pipelines doc

### ISSUE THREAD

**Issue by jbottum** [kubeflow/blog#42]
@hamelsmu Hey Hamel - I think we are ready to unhide the 1.1 blog post.   Yuan asked us to add this url on Multi-user pipelines.  Getting Started with Multi-User Pipelines, https://www.kubeflow.org/docs/pipelines/multi-user/

How do i get access to the file, edit it and then get it posted ?

**Comment by hamelsmu** [comment]
Josh your post is here
https://github.com/kubeflow/blog/blob/master/_posts/2020-07-31-kubeflow-1.1-blog-post.md

You can Unhide it by setting hide: false in the front matter

**Comment by jbottum** [comment]
@cspavlou Chris - will you please review the 1.1 blog post and provide comments and/or a LGTM,

**Comment by jbottum** [comment]
per Community call vote today, we are going to unhide this post

**Comment by jbottum** [comment]
@hamelsmu I need to update the blog post, and change the linked for the 1.1 tutorial to this link, https://www.arrikto.com/model-experimentation/build-an-end-to-end-ml-workflow-from-notebook-to-hp-tuning-to-kubeflow-pipelines-with-kale/,   I did that in the md file and committed it.

**Comment by hamelsmu** [comment]
@jbottum do you need any help or is everything ok

**Comment by jbottum** [comment]
@hamelsmu I just made some updates to include info on the Katib improvements that were missing from the post.   I edited the md file and re-committed.   maybe I did this incorrectly ?

**Comment by hamelsmu** [comment]
@jbottum not sure I think it might be worth it to have someone on your team who is familiar with GitHub to help you out.  Otherwhise please let us know and someone from the community can setup some time to do a pair programming session.  @jlewi what do you think?

**Comment by jlewi** [comment]
@jbottum You will need to open up a PR with these changes. Please ask @yanniszark @kimwnasptd or @StefanoFioravanzo to give you a hand with the PR workflow.

**Comment by hamelsmu** [comment]
I believe this issue can be closed.

@jbottum feel free to reopen if I am mistaken
