### ISSUE TITLE
Use Netlify for previews

### ISSUE THREAD

**Issue by jlewi** [kubeflow/blog#5]
Follow on to #1 

fastpages supports using Netlify to give previews of the website in presubmits

I think we want to enable that.

**Comment by hamelsmu** [comment]
@jlewi 
You need to put two variables into [this repository's secrets](https://github.com/kubeflow/blog/settings/secrets):

1. NETLIFY_AUTH_TOKEN

       - Follow these instructions to get the token: https://docs.netlify.com/cli/get-started/#authentication

2. NETLIFY_SITE_ID

       You can create this by going to the Netlify UI and selecting "New Site From Git"

![image](https://user-images.githubusercontent.com/1483922/87561912-33737f00-c672-11ea-8460-4bf932e9e293.png)

After doing this, select this repo, and ignore all the build command and other form fields you can leave them blank.  Then click on site settings

![image](https://user-images.githubusercontent.com/1483922/87562029-5140e400-c672-11ea-930a-2b2b093712d4.png)

In site settings you will see an`API ID` this is the `NETLIFY_SITE_ID`

**Comment by jlewi** [comment]
Thanks @hamelsmu those steps should be done.

**Comment by hamelsmu** [comment]
@jlewi There is a problem with Netlify auth (ref #5 ) See https://github.com/kubeflow/blog/runs/896633125?check_suite_focus=true#step:15:43

Can you verify that you can deploy this branch via netlify locally?  

You must have the env variables `NETLIFY_AUTH_TOKEN` and `NETLIFY_SITE_ID` set in your local environment

```
npm install netlify-cli -g
make build # this will build the site
netlify deploy --dir _site
```

**Comment by jlewi** [comment]
I updated the secrets maybe I had some newline characters?

**Comment by hamelsmu** [comment]
Thank you I have confirmed this works, closing this issue https://github.com/kubeflow/blog/pull/19
