### ISSUE TITLE
Write a blog post on GSoC student project

### ISSUE THREAD

**Issue by terrytangyuan** [kubeflow/blog#8]
We discussed with our GSoC student @yashjakhotiya today and he's interested in writing up a blog post on his GSoC project. Since the deliverable of the project is a notebook it might be a good idea to try out the new fastpages setup. We can use this issue to discuss further.

cc other mentors @gaocegege @ChanYiLin

**Comment by hamelsmu** [comment]
I suggest reading the fastpages README as a good way to prepare, maybe even play around with a personal blog
